### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [prabhatmittal20/prj-rev-bwfs-tea-cozy#2]
Overall excellent project.

Your html is well structured and organized. You had proper usage of divs, classes, and ids throughout. Your html is well commented making it easier to know what section you are reading through at the time.

CSS is very efficient and didn't have any unnecessary css.  I think this is the smallest number of lines I have seen written to make this website fit the site structure, that is great.  Usually the average is around 150 lines.

To prepare you for the upcoming projects, use a media query to make this site fit properly on a mobile device.

https://www.w3schools.com/css/css_rwd_mediaqueries.asp

The last set of projects will be using media queries for this purpose and this will help prepare you for them.

**Comment by prabhatmittal20** [comment]
I am already working on the media queries. Thanks a lot for the feedback.
